export default [

   {
      "country":"chair",
      "council_code":"unsc",
      "allot":"1",
      "id":"chair23"
   },
   {
      "country":"OC",
      "council_code":"unsc",
      "allot":"1",
      "id":"mofo"
   },
   {
      "country":"vice_chair",
      "council_code":"unsc",
      "allot":"1",
      "id":"vice_chair53"
   },
   {
      "country":"director",
      "council_code":"unsc",
      "allot":"1",
      "id":"director83"
   },
   {
      "country":"Afghanistan",
      "council_code":"unsc",
      "allot":"1",
      "id":"1"
   },
   {  
      "country":"Argentina",
      "council_code":"unsc",
      "allot":"1",
      "id":"2"
   },
   {  
      "country":"Australia",
      "council_code":"unsc",
      "allot":"1",
      "id":"3"
   },
   {  
      "country":"Belgium",
      "council_code":"unsc",
      "allot":"1",
      "id":"4"
   },
   {  
      "country":"Canada",
      "council_code":"unsc",
      "allot":"1",
      "id":"5"
   },
   {  
      "country":"China (Republic of)",
      "council_code":"unsc",
      "allot":"1",
      "id":"6"
   },
   {  
      "country":"Colombia",
      "council_code":"unsc",
      "allot":"1",
      "id":"7"
   },
   {  
      "country":"Czechoslovakia",
      "council_code":"unsc",
      "allot":"1",
      "id":"8"
   },
   {  
      "country":"France",
      "council_code":"unsc",
      "allot":"1",
      "id":"9"
   },
   {  
      "country":"India",
      "council_code":"unsc",
      "allot":"1",
      "id":"10"
   },
   {  
      "country":"Iran",
      "council_code":"unsc",
      "allot":"1",
      "id":"11"
   },
   {  
      "country":"Iraq",
      "council_code":"unsc",
      "allot":"1",
      "id":"12"
   },
   {  
      "country":"Israel",
      "council_code":"unsc",
      "allot":"1",
      "id":"13"
   },
   {  
      "country":"Pakistan",
      "council_code":"unsc",
      "allot":"1",
      "id":"14"
   },
   {  
      "country":"Saudi Arabia",
      "council_code":"unsc",
      "allot":"1",
      "id":"15"
   },
   {  
      "country":"Syria",
      "council_code":"unsc",
      "allot":"0",
      "id":"16"
   },
   {  
      "country":"Ukrainian Soviet Socialist Republic",
      "council_code":"unsc",
      "allot":"1",
      "id":"17"
   },
   {  
      "country":"Union of Soviet Socialist Republics",
      "council_code":"unsc",
      "allot":"1",
      "id":"18"
   },
   {  
      "country":"United Kingdom of Great Britain and Northern Ireland",
      "council_code":"unsc",
      "allot":"1",
      "id":"19"
   },
   {  
      "country":"United States of America",
      "council_code":"unsc",
      "allot":"1",
      "id":"20"
   },
   {
      "country":"chair",
      "council_code":"disec",
      "allot":"1",
      "id":"chair23"
   },
   {
      "country":"vice_chair",
      "council_code":"disec",
      "allot":"1",
      "id":"vice_chair53"
   },
   {
      "country":"director",
      "council_code":"disec",
      "allot":"1",
      "id":"director83"
   },
   {  
      "country":"Afghanistan",
      "council_code":"disec",
      "allot":"1",
      "id":"21"
   },
   {  
      "country":"Albania",
      "council_code":"disec",
      "allot":"1",
      "id":"22"
   },
   {  
      "country":"Algeria",
      "council_code":"disec",
      "allot":"1",
      "id":"23"
   },
   {  
      "country":"Andorra",
      "council_code":"disec",
      "allot":"1",
      "id":"24"
   },
   {  
      "country":"Angola",
      "council_code":"disec",
      "allot":"1",
      "id":"25"
   },
   {  
      "country":"Antigua and Barbuda",
      "council_code":"disec",
      "allot":"0",
      "id":"26"
   },
   {  
      "country":"Argentina",
      "council_code":"disec",
      "allot":"1",
      "id":"27"
   },
   {  
      "country":"Armenia",
      "council_code":"disec",
      "allot":"1",
      "id":"28"
   },
   {  
      "country":"Australia",
      "council_code":"disec",
      "allot":"1",
      "id":"29"
   },
   {  
      "country":"Austria",
      "council_code":"disec",
      "allot":"1",
      "id":"30"
   },
   {  
      "country":"Azerbaijan",
      "council_code":"disec",
      "allot":"1",
      "id":"31"
   },
   {  
      "country":"Bahamas",
      "council_code":"disec",
      "allot":"1",
      "id":"32"
   },
   {  
      "country":"Bahrain",
      "council_code":"disec",
      "allot":"1",
      "id":"33"
   },
   {  
      "country":"Bangladesh",
      "council_code":"disec",
      "allot":"0",
      "id":"34"
   },
   {  
      "country":"Barbados",
      "council_code":"disec",
      "allot":"1",
      "id":"35"
   },
   {  
      "country":"Belarus",
      "council_code":"disec",
      "allot":"1",
      "id":"36"
   },
   {  
      "country":"Belgium",
      "council_code":"disec",
      "allot":"1",
      "id":"37"
   },
   {  
      "country":"Belize",
      "council_code":"disec",
      "allot":"1",
      "id":"38"
   },
   {  
      "country":"Benin",
      "council_code":"disec",
      "allot":"1",
      "id":"39"
   },
   {  
      "country":"Bhutan",
      "council_code":"disec",
      "allot":"0",
      "id":"40"
   },
   {  
      "country":"Bolivia (Plurinational State of )",
      "council_code":"disec",
      "allot":"0",
      "id":"41"
   },
   {  
      "country":"Bosnia and Herzegovina",
      "council_code":"disec",
      "allot":"0",
      "id":"42"
   },
   {  
      "country":"Botswana",
      "council_code":"disec",
      "allot":"1",
      "id":"43"
   },
   {  
      "country":"Brazil",
      "council_code":"disec",
      "allot":"1",
      "id":"44"
   },
   {  
      "country":"Brunei Darussalam",
      "council_code":"disec",
      "allot":"0",
      "id":"45"
   },
   {  
      "country":"Bulgaria",
      "council_code":"disec",
      "allot":"1",
      "id":"46"
   },
   {  
      "country":"Burkina Faso",
      "council_code":"disec",
      "allot":"0",
      "id":"47"
   },
   {  
      "country":"Burundi",
      "council_code":"disec",
      "allot":"1",
      "id":"48"
   },
   {  
      "country":"Cambodia",
      "council_code":"disec",
      "allot":"1",
      "id":"49"
   },
   {  
      "country":"Cameroon",
      "council_code":"disec",
      "allot":"0",
      "id":"50"
   },
   {  
      "country":"Canada",
      "council_code":"disec",
      "allot":"1",
      "id":"51"
   },
   {  
      "country":"Cape Verde",
      "council_code":"disec",
      "allot":"0",
      "id":"52"
   },
   {  
      "country":"Central African Republic",
      "council_code":"disec",
      "allot":"1",
      "id":"53"
   },
   {  
      "country":"Chad",
      "council_code":"disec",
      "allot":"1",
      "id":"54"
   },
   {  
      "country":"Chile",
      "council_code":"disec",
      "allot":"1",
      "id":"55"
   },
   {  
      "country":"China",
      "council_code":"disec",
      "allot":"1",
      "id":"56"
   },
   {
      "country":"OC",
      "council_code":"disec",
      "allot":"1",
      "id":"mofo"
   },
   {  
      "country":"Colombia",
      "council_code":"disec",
      "allot":"1",
      "id":"57"
   },
   {  
      "country":"Comoros",
      "council_code":"disec",
      "allot":"1",
      "id":"58"
   },
   {  
      "country":"Congo",
      "council_code":"disec",
      "allot":"1",
      "id":"59"
   },
   {  
      "country":"Costa Rica",
      "council_code":"disec",
      "allot":"1",
      "id":"60"
   },
   {  
      "country":"Cote d'lvoire",
      "council_code":"disec",
      "allot":"1",
      "id":"61"
   },
   {  
      "country":"Croatia",
      "council_code":"disec",
      "allot":"1",
      "id":"62"
   },
   {  
      "country":"Cuba",
      "council_code":"disec",
      "allot":"1",
      "id":"63"
   },
   {  
      "country":"Cyprus",
      "council_code":"disec",
      "allot":"1",
      "id":"64"
   },
   {  
      "country":"Czech Republic",
      "council_code":"disec",
      "allot":"1",
      "id":"65"
   },
   {  
      "country":"Democratic People's Republic of Korea",
      "council_code":"disec",
      "allot":"1",
      "id":"66"
   },
   {  
      "country":"Democratic Republic of the Congo",
      "council_code":"disec",
      "allot":"1",
      "id":"67"
   },
   {  
      "country":"Denmark",
      "council_code":"disec",
      "allot":"1",
      "id":"68"
   },
   {  
      "country":"Djibouti",
      "council_code":"disec",
      "allot":"0",
      "id":"69"
   },
   {  
      "country":"Dominica",
      "council_code":"disec",
      "allot":"0",
      "id":"70"
   },
   {  
      "country":"Dominican Republic",
      "council_code":"disec",
      "allot":"0",
      "id":"71"
   },
   {  
      "country":"Ecuador",
      "council_code":"disec",
      "allot":"0",
      "id":"72"
   },
   {  
      "country":"Egypt",
      "council_code":"disec",
      "allot":"1",
      "id":"73"
   },
   {  
      "country":"El Salvador",
      "council_code":"disec",
      "allot":"0",
      "id":"74"
   },
   {  
      "country":"Equatorial Guinea",
      "council_code":"disec",
      "allot":"0",
      "id":"75"
   },
   {  
      "country":"Eritrea",
      "council_code":"disec",
      "allot":"0",
      "id":"76"
   },
   {  
      "country":"Estonia",
      "council_code":"disec",
      "allot":"0",
      "id":"77"
   },
   {  
      "country":"Ethiopia",
      "council_code":"disec",
      "allot":"1",
      "id":"78"
   },
   {  
      "country":"Fiji",
      "council_code":"disec",
      "allot":"1",
      "id":"79"
   },
   {  
      "country":"Finland",
      "council_code":"disec",
      "allot":"1",
      "id":"80"
   },
   {  
      "country":"France",
      "council_code":"disec",
      "allot":"1",
      "id":"81"
   },
   {  
      "country":"Gabon",
      "council_code":"disec",
      "allot":"0",
      "id":"82"
   },
   {  
      "country":"Gambia",
      "council_code":"disec",
      "allot":"1",
      "id":"83"
   },
   {  
      "country":"Georgia",
      "council_code":"disec",
      "allot":"1",
      "id":"84"
   },
   {  
      "country":"Germany",
      "council_code":"disec",
      "allot":"1",
      "id":"85"
   },
   {  
      "country":"Ghana",
      "council_code":"disec",
      "allot":"1",
      "id":"86"
   },
   {  
      "country":"Greece",
      "council_code":"disec",
      "allot":"1",
      "id":"87"
   },
   {  
      "country":"Grenada",
      "council_code":"disec",
      "allot":"0",
      "id":"88"
   },
   {  
      "country":"Guatemala",
      "council_code":"disec",
      "allot":"1",
      "id":"89"
   },
   {  
      "country":"Guinea",
      "council_code":"disec",
      "allot":"0",
      "id":"90"
   },
   {  
      "country":"Guinea-Bissau",
      "council_code":"disec",
      "allot":"0",
      "id":"91"
   },
   {  
      "country":"Guyana",
      "council_code":"disec",
      "allot":"0",
      "id":"92"
   },
   {  
      "country":"Haiti",
      "council_code":"disec",
      "allot":"1",
      "id":"93"
   },
   {  
      "country":"Honduras",
      "council_code":"disec",
      "allot":"0",
      "id":"94"
   },
   {  
      "country":"Hungary",
      "council_code":"disec",
      "allot":"1",
      "id":"95"
   },
   {  
      "country":"Iceland",
      "council_code":"disec",
      "allot":"1",
      "id":"96"
   },
   {  
      "country":"India",
      "council_code":"disec",
      "allot":"1",
      "id":"97"
   },
   {  
      "country":"Indonesia",
      "council_code":"disec",
      "allot":"1",
      "id":"98"
   },
   {  
      "country":"Iran (Islamic Republic of)",
      "council_code":"disec",
      "allot":"1",
      "id":"99"
   },
   {  
      "country":"Iraq",
      "council_code":"disec",
      "allot":"1",
      "id":"100"
   },
   {  
      "country":"Ireland",
      "council_code":"disec",
      "allot":"1",
      "id":"101"
   },
   {  
      "country":"Israel",
      "council_code":"disec",
      "allot":"1",
      "id":"102"
   },
   {  
      "country":"Italy",
      "council_code":"disec",
      "allot":"1",
      "id":"103"
   },
   {  
      "country":"Jamaica",
      "council_code":"disec",
      "allot":"1",
      "id":"104"
   },
   {  
      "country":"Japan",
      "council_code":"disec",
      "allot":"1",
      "id":"105"
   },
   {  
      "country":"Jordan",
      "council_code":"disec",
      "allot":"1",
      "id":"106"
   },
   {  
      "country":"Kazakhstan",
      "council_code":"disec",
      "allot":"1",
      "id":"107"
   },
   {  
      "country":"Kenya",
      "council_code":"disec",
      "allot":"1",
      "id":"108"
   },
   {  
      "country":"Kiribati",
      "council_code":"disec",
      "allot":"0",
      "id":"109"
   },
   {  
      "country":"Kuwait",
      "council_code":"disec",
      "allot":"1",
      "id":"110"
   },
   {  
      "country":"Kyrgzystan",
      "council_code":"disec",
      "allot":"1",
      "id":"111"
   },
   {  
      "country":"Lao People's Democratic Republic",
      "council_code":"disec",
      "allot":"0",
      "id":"112"
   },
   {  
      "country":"Latvia",
      "council_code":"disec",
      "allot":"1",
      "id":"113"
   },
   {  
      "country":"Lebanon",
      "council_code":"disec",
      "allot":"1",
      "id":"114"
   },
   {  
      "country":"Lesotho",
      "council_code":"disec",
      "allot":"0",
      "id":"115"
   },
   {  
      "country":"Liberia",
      "council_code":"disec",
      "allot":"1",
      "id":"116"
   },
   {  
      "country":"Libya",
      "council_code":"disec",
      "allot":"1",
      "id":"117"
   },
   {  
      "country":"Liechtenstein",
      "council_code":"disec",
      "allot":"1",
      "id":"118"
   },
   {  
      "country":"Lithuania",
      "council_code":"disec",
      "allot":"1",
      "id":"119"
   },
   {  
      "country":"Luxemborg",
      "council_code":"disec",
      "allot":"1",
      "id":"120"
   },
   {  
      "country":"Madagascar",
      "council_code":"disec",
      "allot":"0",
      "id":"121"
   },
   {  
      "country":"Malawi",
      "council_code":"disec",
      "allot":"0",
      "id":"122"
   },
   {  
      "country":"Malaysia",
      "council_code":"disec",
      "allot":"1",
      "id":"123"
   },
   {  
      "country":"Maldives",
      "council_code":"disec",
      "allot":"1",
      "id":"124"
   },
   {  
      "country":"Mali",
      "council_code":"disec",
      "allot":"0",
      "id":"125"
   },
   {  
      "country":"Malta",
      "council_code":"disec",
      "allot":"1",
      "id":"126"
   },
   {  
      "country":"Marshall Islands",
      "council_code":"disec",
      "allot":"0",
      "id":"127"
   },
   {  
      "country":"Mauritania",
      "council_code":"disec",
      "allot":"1",
      "id":"128"
   },
   {  
      "country":"Mauritius",
      "council_code":"disec",
      "allot":"0",
      "id":"129"
   },
   {  
      "country":"Mexico",
      "council_code":"disec",
      "allot":"1",
      "id":"130"
   },
   {  
      "country":"Micronesia (Federal States of)",
      "council_code":"disec",
      "allot":"0",
      "id":"131"
   },
   {  
      "country":"Monaco",
      "council_code":"disec",
      "allot":"0",
      "id":"132"
   },
   {  
      "country":"Mongolia",
      "council_code":"disec",
      "allot":"0",
      "id":"133"
   },
   {  
      "country":"Montenegro",
      "council_code":"disec",
      "allot":"0",
      "id":"134"
   },
   {  
      "country":"Morocco",
      "council_code":"disec",
      "allot":"1",
      "id":"135"
   },
   {  
      "country":"Mozambique",
      "council_code":"disec",
      "allot":"0",
      "id":"136"
   },
   {  
      "country":"Myanmar",
      "council_code":"disec",
      "allot":"1",
      "id":"137"
   },
   {  
      "country":"Namibia",
      "council_code":"disec",
      "allot":"0",
      "id":"138"
   },
   {  
      "country":"Nauru",
      "council_code":"disec",
      "allot":"0",
      "id":"139"
   },
   {  
      "country":"Nepal",
      "council_code":"disec",
      "allot":"1",
      "id":"140"
   },
   {  
      "country":"Netherlands",
      "council_code":"disec",
      "allot":"1",
      "id":"141"
   },
   {  
      "country":"New Zealand",
      "council_code":"disec",
      "allot":"1",
      "id":"142"
   },
   {  
      "country":"Nicaragua",
      "council_code":"disec",
      "allot":"0",
      "id":"143"
   },
   {  
      "country":"Niger",
      "council_code":"disec",
      "allot":"0",
      "id":"144"
   },
   {  
      "country":"Nigeria",
      "council_code":"disec",
      "allot":"1",
      "id":"145"
   },
   {  
      "country":"Norway",
      "council_code":"disec",
      "allot":"1",
      "id":"146"
   },
   {  
      "country":"Oman",
      "council_code":"disec",
      "allot":"1",
      "id":"147"
   },
   {  
      "country":"Pakistan",
      "council_code":"disec",
      "allot":"1",
      "id":"148"
   },
   {  
      "country":"Palau",
      "council_code":"disec",
      "allot":"0",
      "id":"149"
   },
   {  
      "country":"Palestine(O)",
      "council_code":"disec",
      "allot":"1",
      "id":"150"
   },
   {  
      "country":"Panama",
      "council_code":"disec",
      "allot":"1",
      "id":"151"
   },
   {  
      "country":"Papua New Guinea",
      "council_code":"disec",
      "allot":"0",
      "id":"152"
   },
   {  
      "country":"Paraguay",
      "council_code":"disec",
      "allot":"1",
      "id":"153"
   },
   {  
      "country":"Peru",
      "council_code":"disec",
      "allot":"0",
      "id":"154"
   },
   {  
      "country":"Phillipines",
      "council_code":"disec",
      "allot":"1",
      "id":"155"
   },
   {  
      "country":"Poland",
      "council_code":"disec",
      "allot":"1",
      "id":"156"
   },
   {  
      "country":"Portugal",
      "council_code":"disec",
      "allot":"1",
      "id":"157"
   },
   {  
      "country":"Qatar",
      "council_code":"disec",
      "allot":"1",
      "id":"158"
   },
   {  
      "country":"Republic of Korea",
      "council_code":"disec",
      "allot":"1",
      "id":"159"
   },
   {  
      "country":"Republic of Moldova",
      "council_code":"disec",
      "allot":"0",
      "id":"160"
   },
   {  
      "country":"Romania",
      "council_code":"disec",
      "allot":"1",
      "id":"161"
   },
   {  
      "country":"Russian Federation",
      "council_code":"disec",
      "allot":"1",
      "id":"162"
   },
   {  
      "country":"Rwanda",
      "council_code":"disec",
      "allot":"1",
      "id":"163"
   },
   {  
      "country":"Saint Kitts and Nevis",
      "council_code":"disec",
      "allot":"0",
      "id":"164"
   },
   {  
      "country":"Saint Lucia",
      "council_code":"disec",
      "allot":"0",
      "id":"165"
   },
   {  
      "country":"Saint Vincent and the Grenadines",
      "council_code":"disec",
      "allot":"0",
      "id":"166"
   },
   {  
      "country":"Samoa",
      "council_code":"disec",
      "allot":"0",
      "id":"167"
   },
   {  
      "country":"San Marino",
      "council_code":"disec",
      "allot":"0",
      "id":"168"
   },
   {  
      "country":"Sao Tome and Principe",
      "council_code":"disec",
      "allot":"0",
      "id":"169"
   },
   {  
      "country":"Saudi Arabia",
      "council_code":"disec",
      "allot":"0",
      "id":"170"
   },
   {  
      "country":"Senegal",
      "council_code":"disec",
      "allot":"1",
      "id":"171"
   },
   {  
      "country":"Serbia",
      "council_code":"disec",
      "allot":"1",
      "id":"172"
   },
   {  
      "country":"Seychelles",
      "council_code":"disec",
      "allot":"0",
      "id":"173"
   },
   {  
      "country":"Sierra Leone",
      "council_code":"disec",
      "allot":"0",
      "id":"174"
   },
   {  
      "country":"Singapore",
      "council_code":"disec",
      "allot":"1",
      "id":"175"
   },
   {  
      "country":"Slovakia",
      "council_code":"disec",
      "allot":"1",
      "id":"176"
   },
   {  
      "country":"Slovenia",
      "council_code":"disec",
      "allot":"0",
      "id":"177"
   },
   {  
      "country":"Solomon Islands",
      "council_code":"disec",
      "allot":"0",
      "id":"178"
   },
   {  
      "country":"Somalia",
      "council_code":"disec",
      "allot":"1",
      "id":"179"
   },
   {  
      "country":"South Africa",
      "council_code":"disec",
      "allot":"1",
      "id":"180"
   },
   {  
      "country":"South Sudan",
      "council_code":"disec",
      "allot":"1",
      "id":"181"
   },
   {  
      "country":"Spain",
      "council_code":"disec",
      "allot":"1",
      "id":"182"
   },
   {  
      "country":"Sri Lanka",
      "council_code":"disec",
      "allot":"1",
      "id":"183"
   },
   {  
      "country":"Sudan",
      "council_code":"disec",
      "allot":"0",
      "id":"184"
   },
   {  
      "country":"Suriname",
      "council_code":"disec",
      "allot":"0",
      "id":"185"
   },
   {  
      "country":"Swaziland",
      "council_code":"disec",
      "allot":"0",
      "id":"186"
   },
   {  
      "country":"Sweden",
      "council_code":"disec",
      "allot":"1",
      "id":"187"
   },
   {  
      "country":"Switzerland",
      "council_code":"disec",
      "allot":"1",
      "id":"188"
   },
   {  
      "country":"Syrian Arab Republic",
      "council_code":"disec",
      "allot":"1",
      "id":"189"
   },
   {  
      "country":"Tajikistan",
      "council_code":"disec",
      "allot":"1",
      "id":"190"
   },
   {  
      "country":"Thailand",
      "council_code":"disec",
      "allot":"1",
      "id":"191"
   },
   {  
      "country":"The former Yugoslav Republic of Macedonia",
      "council_code":"disec",
      "allot":"1",
      "id":"192"
   },
   {  
      "country":"Timor-Leste",
      "council_code":"disec",
      "allot":"1",
      "id":"193"
   },
   {  
      "country":"Togo",
      "council_code":"disec",
      "allot":"0",
      "id":"194"
   },
   {  
      "country":"Tonga",
      "council_code":"disec",
      "allot":"0",
      "id":"195"
   },
   {  
      "country":"Trinidad and Tobago",
      "council_code":"disec",
      "allot":"0",
      "id":"196"
   },
   {  
      "country":"Tunisia",
      "council_code":"disec",
      "allot":"1",
      "id":"197"
   },
   {  
      "country":"Turkey",
      "council_code":"disec",
      "allot":"1",
      "id":"198"
   },
   {  
      "country":"Turkmenistan",
      "council_code":"disec",
      "allot":"1",
      "id":"199"
   },
   {  
      "country":"Tuvalu",
      "council_code":"disec",
      "allot":"0",
      "id":"200"
   },
   {  
      "country":"Uganda",
      "council_code":"disec",
      "allot":"0",
      "id":"201"
   },
   {  
      "country":"Ukraine",
      "council_code":"disec",
      "allot":"0",
      "id":"202"
   },
   {  
      "country":"United Arab Emirates",
      "council_code":"disec",
      "allot":"1",
      "id":"203"
   },
   {  
      "country":"United Kingdom",
      "council_code":"disec",
      "allot":"1",
      "id":"204"
   },
   {  
      "country":"United Republic of Tanzania",
      "council_code":"disec",
      "allot":"0",
      "id":"205"
   },
   {  
      "country":"United States of America",
      "council_code":"disec",
      "allot":"1",
      "id":"206"
   },
   {  
      "country":"Uruguay",
      "council_code":"disec",
      "allot":"1",
      "id":"207"
   },
   {  
      "country":"Uzbekistan",
      "council_code":"disec",
      "allot":"1",
      "id":"208"
   },
   {  
      "country":"Vanuatu",
      "council_code":"disec",
      "allot":"0",
      "id":"209"
   },
   {  
      "country":"Venezuela (Bolivarian Republic of)",
      "council_code":"disec",
      "allot":"0",
      "id":"210"
   },
   {  
      "country":"Yemen",
      "council_code":"disec",
      "allot":"0",
      "id":"212"
   },
   {  
      "country":"Zambia",
      "council_code":"disec",
      "allot":"0",
      "id":"213"
   },
   {  
      "country":"Zimbabwe",
      "council_code":"disec",
      "allot":"0",
      "id":"214"
   },
   {  
      "country":"AFGHANISTAN",
      "council_code":"unhrc",
      "allot":"1",
      "id":"215"
   },
   {  
      "country":"ALBANIA ",
      "council_code":"unhrc",
      "allot":"1",
      "id":"216"
   },
   {  
      "country":"AMNESTY INTERNATIONAL",
      "council_code":"unhrc",
      "allot":"1",
      "id":"217"
   },
   {  
      "country":"BANGLADESH",
      "council_code":"unhrc",
      "allot":"1",
      "id":"218"
   },
   {
      "country":"chair",
      "council_code":"unhrc",
      "allot":"1",
      "id":"chair23"
   },
   {
      "country":"vice_chair",
      "council_code":"unhrc",
      "allot":"1",
      "id":"vice_chair53"
   },
   {
      "country":"director",
      "council_code":"unhrc",
      "allot":"1",
      "id":"director83"
   },
   {  
      "country":"BELGIUM",
      "council_code":"unhrc",
      "allot":"1",
      "id":"219"
   },
   {  
      "country":"BOLIVIA",
      "council_code":"unhrc",
      "allot":"0",
      "id":"220"
   },
   {  
      "country":"BOSNIA & HERZEGOVINA",
      "council_code":"unhrc",
      "allot":"1",
      "id":"221"
   },
   {
      "country":"OC",
      "council_code":"disec",
      "allot":"1",
      "id":"mofo"
   },
   {  
      "country":"BOTSWANA ",
      "council_code":"unhrc",
      "allot":"1",
      "id":"222"
   },
   {  
      "country":"BRAZIL",
      "council_code":"unhrc",
      "allot":"1",
      "id":"223"
   },
   {  
      "country":"BURUNDI",
      "council_code":"unhrc",
      "allot":"1",
      "id":"224"
   },
   {  
      "country":"CANADA",
      "council_code":"unhrc",
      "allot":"1",
      "id":"225"
   },
   {  
      "country":"CHINA",
      "council_code":"unhrc",
      "allot":"1",
      "id":"226"
   },
   {  
      "country":"CONGO",
      "council_code":"unhrc",
      "allot":"1",
      "id":"227"
   },
   {  
      "country":"COTE D'IVOIRE",
      "council_code":"unhrc",
      "allot":"1",
      "id":"228"
   },
   {  
      "country":"CROATIA",
      "council_code":"unhrc",
      "allot":"1",
      "id":"229"
   },
   {  
      "country":"CUBA",
      "council_code":"unhrc",
      "allot":"1",
      "id":"230"
   },
   {  
      "country":"DENMARK",
      "council_code":"unhrc",
      "allot":"1",
      "id":"231"
   },
   {  
      "country":"ECUADOR",
      "council_code":"unhrc",
      "allot":"1",
      "id":"232"
   },
   {  
      "country":"EGYPT",
      "council_code":"unhrc",
      "allot":"1",
      "id":"233"
   },
   {  
      "country":"EL SALVADOR",
      "council_code":"unhrc",
      "allot":"1",
      "id":"234"
   },
   {  
      "country":"ETHIOPIA",
      "council_code":"unhrc",
      "allot":"1",
      "id":"235"
   },
   {  
      "country":"FRANCE",
      "council_code":"unhrc",
      "allot":"1",
      "id":"236"
   },
   {  
      "country":"GEORGIA",
      "council_code":"unhrc",
      "allot":"1",
      "id":"237"
   },
   {  
      "country":"GERMANY",
      "council_code":"unhrc",
      "allot":"1",
      "id":"238"
   },
   {
      "country":"OC",
      "council_code":"unhrc",
      "allot":"1",
      "id":"mofo"
   },
   {  
      "country":"GHANA",
      "council_code":"unhrc",
      "allot":"1",
      "id":"239"
   },
   {  
      "country":"HUNGARY",
      "council_code":"unhrc",
      "allot":"1",
      "id":"240"
   },
   {  
      "country":"INDIA",
      "council_code":"unhrc",
      "allot":"1",
      "id":"241"
   },
   {  
      "country":"INDONESIA",
      "council_code":"unhrc",
      "allot":"1",
      "id":"242"
   },
   {  
      "country":"IRAN",
      "council_code":"unhrc",
      "allot":"1",
      "id":"243"
   },
   {  
      "country":"IRAQ",
      "council_code":"unhrc",
      "allot":"1",
      "id":"244"
   },
   {  
      "country":"JAPAN",
      "council_code":"unhrc",
      "allot":"1",
      "id":"245"
   },
   {  
      "country":"KENYA",
      "council_code":"unhrc",
      "allot":"1",
      "id":"246"
   },
   {  
      "country":"KYRGYZSTAN",
      "council_code":"unhrc",
      "allot":"1",
      "id":"247"
   },
   {  
      "country":"LATVIA",
      "council_code":"unhrc",
      "allot":"1",
      "id":"248"
   },
   {  
      "country":"LIBYA",
      "council_code":"unhrc",
      "allot":"1",
      "id":"249"
   },
   {  
      "country":"MONGOLIA",
      "council_code":"unhrc",
      "allot":"1",
      "id":"250"
   },
   {  
      "country":"NETHERLANDS",
      "council_code":"unhrc",
      "allot":"1",
      "id":"251"
   },
   {  
      "country":"NIGERIA",
      "council_code":"unhrc",
      "allot":"1",
      "id":"252"
   },
   {  
      "country":"PAKISTAN",
      "council_code":"unhrc",
      "allot":"1",
      "id":"253"
   },
   {  
      "country":"PANAMA",
      "council_code":"unhrc",
      "allot":"1",
      "id":"254"
   },
   {  
      "country":"PARAGUAY",
      "council_code":"unhrc",
      "allot":"1",
      "id":"255"
   },
   {  
      "country":"PHILIPPINES",
      "council_code":"unhrc",
      "allot":"1",
      "id":"256"
   },
   {  
      "country":"PORTUGAL",
      "council_code":"unhrc",
      "allot":"1",
      "id":"257"
   },
   {  
      "country":"QATAR",
      "council_code":"unhrc",
      "allot":"1",
      "id":"258"
   },
   {  
      "country":"REPUBLIC OF KOREA",
      "council_code":"unhrc",
      "allot":"1",
      "id":"259"
   },
   {  
      "country":"RUSSIA",
      "council_code":"unhrc",
      "allot":"1",
      "id":"260"
   },
   {  
      "country":"RWANDA",
      "council_code":"unhrc",
      "allot":"1",
      "id":"261"
   },
   {  
      "country":"SAUDI ARABIA",
      "council_code":"unhrc",
      "allot":"1",
      "id":"262"
   },
   {  
      "country":"SLOVENIA",
      "council_code":"unhrc",
      "allot":"1",
      "id":"263"
   },
   {  
      "country":"SOUTH AFRICA",
      "council_code":"unhrc",
      "allot":"1",
      "id":"264"
   },
   {  
      "country":"SWEDEN",
      "council_code":"unhrc",
      "allot":"1",
      "id":"265"
   },
   {  
      "country":"SWITZERLAND",
      "council_code":"unhrc",
      "allot":"1",
      "id":"266"
   },
   {  
      "country":"TOGO",
      "council_code":"unhrc",
      "allot":"1",
      "id":"267"
   },
   {  
      "country":"TUNISIA",
      "council_code":"unhrc",
      "allot":"1",
      "id":"268"
   },
   {  
      "country":"UNITED ARAB EMIRATES",
      "council_code":"unhrc",
      "allot":"1",
      "id":"269"
   },
   {  
      "country":"UNITED KINGDOM",
      "council_code":"unhrc",
      "allot":"1",
      "id":"270"
   },
   {  
      "country":"UNITED STATES OF AMERICA",
      "council_code":"unhrc",
      "allot":"1",
      "id":"271"
   },
   {  
      "country":"VENEZUELA",
      "council_code":"unhrc",
      "allot":"1",
      "id":"272"
   },
   {  
      "country":"Afghanistan",
      "council_code":"iaea",
      "allot":"1",
      "id":"273"
   },
   {  
      "country":"Algeria",
      "council_code":"iaea",
      "allot":"1",
      "id":"274"
   },
   {
      "country":"chair",
      "council_code":"iaea",
      "allot":"1",
      "id":"chair23"
   },
   {
      "country":"vice_chair",
      "council_code":"iaea",
      "allot":"1",
      "id":"vice_chair53"
   },
   {
      "country":"director",
      "council_code":"iaea",
      "allot":"1",
      "id":"director83"
   },
   {  
      "country":"Argentina",
      "council_code":"iaea",
      "allot":"1",
      "id":"275"
   },
   {
      "country":"OC",
      "council_code":"iaea",
      "allot":"1",
      "id":"mofo"
   },
   {  
      "country":"Australia",
      "council_code":"iaea",
      "allot":"0",
      "id":"276"
   },
   {  
      "country":"Central African Republic",
      "council_code":"iaea",
      "allot":"1",
      "id":"277"
   },
   {  
      "country":"Azerbaijan",
      "council_code":"iaea",
      "allot":"1",
      "id":"278"
   },
   {  
      "country":"Belgium",
      "council_code":"iaea",
      "allot":"1",
      "id":"279"
   },
   {  
      "country":"Brazil",
      "council_code":"iaea",
      "allot":"0",
      "id":"280"
   },
   {  
      "country":"Bulgaria",
      "council_code":"iaea",
      "allot":"1",
      "id":"281"
   },
   {  
      "country":"Cameroon",
      "council_code":"iaea",
      "allot":"1",
      "id":"282"
   },
   {  
      "country":"Canada",
      "council_code":"iaea",
      "allot":"1",
      "id":"283"
   },
   {  
      "country":"Chad",
      "council_code":"iaea",
      "allot":"1",
      "id":"284"
   },
   {  
      "country":"Chile",
      "council_code":"iaea",
      "allot":"1",
      "id":"285"
   },
   {  
      "country":"China",
      "council_code":"iaea",
      "allot":"1",
      "id":"286"
   },
   {  
      "country":"Democratic Republic of the Congo",
      "council_code":"iaea",
      "allot":"1",
      "id":"287"
   },
   {  
      "country":"Costa Rica",
      "council_code":"iaea",
      "allot":"0",
      "id":"288"
   },
   {  
      "country":"Czech Republic",
      "council_code":"iaea",
      "allot":"0",
      "id":"289"
   },
   {  
      "country":"Denmark",
      "council_code":"iaea",
      "allot":"1",
      "id":"290"
   },
   {  
      "country":"DPRK",
      "council_code":"iaea",
      "allot":"1",
      "id":"291"
   },
   {  
      "country":"Egypt",
      "council_code":"iaea",
      "allot":"0",
      "id":"292"
   },
   {  
      "country":"Finland",
      "council_code":"iaea",
      "allot":"0",
      "id":"293"
   },
   {  
      "country":"France",
      "council_code":"iaea",
      "allot":"1",
      "id":"294"
   },
   {  
      "country":"Germany",
      "council_code":"iaea",
      "allot":"1",
      "id":"295"
   },
   {  
      "country":"Greece",
      "council_code":"iaea",
      "allot":"1",
      "id":"296"
   },
   {  
      "country":"Guatemala",
      "council_code":"iaea",
      "allot":"1",
      "id":"297"
   },
   {  
      "country":"Hungary",
      "council_code":"iaea",
      "allot":"1",
      "id":"298"
   },
   {  
      "country":"Iceland",
      "council_code":"iaea",
      "allot":"1",
      "id":"299"
   },
   {  
      "country":"India",
      "council_code":"iaea",
      "allot":"1",
      "id":"300"
   },
   {  
      "country":"Indonesia",
      "council_code":"iaea",
      "allot":"1",
      "id":"301"
   },
   {  
      "country":"Iran",
      "council_code":"iaea",
      "allot":"1",
      "id":"302"
   },
   {  
      "country":"Iraq",
      "council_code":"iaea",
      "allot":"0",
      "id":"303"
   },
   {  
      "country":"Ireland",
      "council_code":"iaea",
      "allot":"1",
      "id":"304"
   },
   {  
      "country":"Israel",
      "council_code":"iaea",
      "allot":"1",
      "id":"305"
   },
   {  
      "country":"Italy",
      "council_code":"iaea",
      "allot":"1",
      "id":"306"
   },
   {  
      "country":"Japan",
      "council_code":"iaea",
      "allot":"1",
      "id":"307"
   },
   {  
      "country":"Jordan",
      "council_code":"iaea",
      "allot":"1",
      "id":"308"
   },
   {  
      "country":"Kazakhstan",
      "council_code":"iaea",
      "allot":"1",
      "id":"309"
   },
   {  
      "country":"Kyrgyzstan",
      "council_code":"iaea",
      "allot":"0",
      "id":"310"
   },
   {  
      "country":"Libya",
      "council_code":"iaea",
      "allot":"1",
      "id":"311"
   },
   {  
      "country":"Luxembourg",
      "council_code":"iaea",
      "allot":"1",
      "id":"312"
   },
   {  
      "country":"Malaysia",
      "council_code":"iaea",
      "allot":"1",
      "id":"313"
   },
   {  
      "country":"Mauritius",
      "council_code":"iaea",
      "allot":"1",
      "id":"314"
   },
   {  
      "country":"Mexico",
      "council_code":"iaea",
      "allot":"1",
      "id":"315"
   },
   {  
      "country":"Morocco",
      "council_code":"iaea",
      "allot":"1",
      "id":"316"
   },
   {  
      "country":"Netherlands",
      "council_code":"iaea",
      "allot":"1",
      "id":"317"
   },
   {  
      "country":"New Zealand",
      "council_code":"iaea",
      "allot":"1",
      "id":"318"
   },
   {  
      "country":"Nigeria",
      "council_code":"iaea",
      "allot":"1",
      "id":"319"
   },
   {  
      "country":"Pakistan",
      "council_code":"iaea",
      "allot":"1",
      "id":"320"
   },
   {  
      "country":"Palestine",
      "council_code":"iaea",
      "allot":"1",
      "id":"321"
   },
   {  
      "country":"Panama",
      "council_code":"iaea",
      "allot":"1",
      "id":"322"
   },
   {  
      "country":"Peru",
      "council_code":"iaea",
      "allot":"1",
      "id":"323"
   },
   {  
      "country":"Philippines",
      "council_code":"iaea",
      "allot":"1",
      "id":"324"
   },
   {  
      "country":"Portugal",
      "council_code":"iaea",
      "allot":"1",
      "id":"325"
   },
   {  
      "country":"Romania",
      "council_code":"iaea",
      "allot":"1",
      "id":"326"
   },
   {  
      "country":"Russia",
      "council_code":"iaea",
      "allot":"1",
      "id":"327"
   },
   {  
      "country":"Saudi Arabia",
      "council_code":"iaea",
      "allot":"1",
      "id":"328"
   },
   {  
      "country":"Seychelles",
      "council_code":"iaea",
      "allot":"1",
      "id":"329"
   },
   {  
      "country":"Singapore",
      "council_code":"iaea",
      "allot":"1",
      "id":"330"
   },
   {  
      "country":"South Africa",
      "council_code":"iaea",
      "allot":"1",
      "id":"331"
   },
   {  
      "country":"South Korea",
      "council_code":"iaea",
      "allot":"1",
      "id":"332"
   },
   {  
      "country":"Spain",
      "council_code":"iaea",
      "allot":"1",
      "id":"333"
   },
   {  
      "country":"Sri Lanka",
      "council_code":"iaea",
      "allot":"1",
      "id":"334"
   },
   {  
      "country":"Sweden",
      "council_code":"iaea",
      "allot":"1",
      "id":"335"
   },
   {  
      "country":"Switzerland",
      "council_code":"iaea",
      "allot":"1",
      "id":"336"
   },
   {  
      "country":"Syria",
      "council_code":"iaea",
      "allot":"1",
      "id":"337"
   },
   {  
      "country":"Thailand",
      "council_code":"iaea",
      "allot":"1",
      "id":"338"
   },
   {  
      "country":"Tunisia",
      "council_code":"iaea",
      "allot":"1",
      "id":"339"
   },
   {  
      "country":"Turkey",
      "council_code":"iaea",
      "allot":"0",
      "id":"340"
   },
   {  
      "country":"UAE",
      "council_code":"iaea",
      "allot":"1",
      "id":"341"
   },
   {  
      "country":"UK",
      "council_code":"iaea",
      "allot":"0",
      "id":"342"
   },
   {  
      "country":"Ukraine",
      "council_code":"iaea",
      "allot":"0",
      "id":"343"
   },
   {  
      "country":"Uruguay",
      "council_code":"iaea",
      "allot":"1",
      "id":"344"
   },
   {  
      "country":"USA",
      "council_code":"iaea",
      "allot":"1",
      "id":"345"
   },
   {  
      "country":"Vietnam",
      "council_code":"iaea",
      "allot":"1",
      "id":"346"
   },
   {  
      "country":"Yemen",
      "council_code":"iaea",
      "allot":"1",
      "id":"347"
   },
   {
      "country":"chair",
      "council_code":"osce",
      "allot":"1",
      "id":"chair23"
   },
   {
      "country":"vice_chair",
      "council_code":"osce",
      "allot":"1",
      "id":"vice_chair53"
   },
   {
      "country":"director",
      "council_code":"osce",
      "allot":"1",
      "id":"director83"
   },
   {  
      "country":"Afghanistan",
      "council_code":"osce",
      "allot":"1",
      "id":"348"
   },
   {  
      "country":"Albania",
      "council_code":"osce",
      "allot":"1",
      "id":"349"
   },
   {  
      "country":"Algeria",
      "council_code":"osce",
      "allot":"1",
      "id":"350"
   },
   {  
      "country":"Andorra",
      "council_code":"osce",
      "allot":"1",
      "id":"351"
   },
   {  
      "country":"Armenia",
      "council_code":"osce",
      "allot":"1",
      "id":"352"
   },
   {  
      "country":"Australia",
      "council_code":"osce",
      "allot":"1",
      "id":"353"
   },
   {  
      "country":"Austria",
      "council_code":"osce",
      "allot":"1",
      "id":"354"
   },
   {  
      "country":"Azerbaijan",
      "council_code":"osce",
      "allot":"0",
      "id":"355"
   },
   {  
      "country":"Belarus",
      "council_code":"osce",
      "allot":"1",
      "id":"356"
   },
   {  
      "country":"Belgium",
      "council_code":"osce",
      "allot":"1",
      "id":"357"
   },
   {  
      "country":"Bosnia and Herzegovina",
      "council_code":"osce",
      "allot":"1",
      "id":"358"
   },
   {  
      "country":"Bulgaria",
      "council_code":"osce",
      "allot":"1",
      "id":"359"
   },
   {  
      "country":"Canada",
      "council_code":"osce",
      "allot":"1",
      "id":"360"
   },
   {  
      "country":"Croatia",
      "council_code":"osce",
      "allot":"0",
      "id":"361"
   },
   {  
      "country":"Cyprus",
      "council_code":"osce",
      "allot":"1",
      "id":"362"
   },
   {  
      "country":"Czech Republic",
      "council_code":"osce",
      "allot":"0",
      "id":"363"
   },
   {  
      "country":"Denmark",
      "council_code":"osce",
      "allot":"1",
      "id":"364"
   },
   {  
      "country":"Egypt",
      "council_code":"osce",
      "allot":"1",
      "id":"365"
   },
   {  
      "country":"Estonia",
      "council_code":"osce",
      "allot":"1",
      "id":"366"
   },
   {
      "country":"OC",
      "council_code":"osce",
      "allot":"1",
      "id":"mofo"
   },
   {  
      "country":"Finland",
      "council_code":"osce",
      "allot":"1",
      "id":"367"
   },
   {  
      "country":"France",
      "council_code":"osce",
      "allot":"1",
      "id":"368"
   },
   {  
      "country":"Georgia",
      "council_code":"osce",
      "allot":"1",
      "id":"369"
   },
   {  
      "country":"Germany",
      "council_code":"osce",
      "allot":"1",
      "id":"370"
   },
   {  
      "country":"Greece",
      "council_code":"osce",
      "allot":"1",
      "id":"371"
   },
   {  
      "country":"Holy See",
      "council_code":"osce",
      "allot":"1",
      "id":"372"
   },
   {  
      "country":"Hungary",
      "council_code":"osce",
      "allot":"1",
      "id":"373"
   },
   {  
      "country":"Iceland",
      "council_code":"osce",
      "allot":"1",
      "id":"374"
   },
   {  
      "country":"Ireland",
      "council_code":"osce",
      "allot":"1",
      "id":"375"
   },
   {  
      "country":"Israel",
      "council_code":"osce",
      "allot":"1",
      "id":"376"
   },
   {  
      "country":"Italy",
      "council_code":"osce",
      "allot":"1",
      "id":"377"
   },
   {  
      "country":"Japan",
      "council_code":"osce",
      "allot":"1",
      "id":"378"
   },
   {  
      "country":"Jordan",
      "council_code":"osce",
      "allot":"1",
      "id":"379"
   },
   {  
      "country":"Kazakhstan",
      "council_code":"osce",
      "allot":"0",
      "id":"380"
   },
   {  
      "country":"Kyrgyzstan",
      "council_code":"osce",
      "allot":"1",
      "id":"381"
   },
   {  
      "country":"Latvia",
      "council_code":"osce",
      "allot":"0",
      "id":"382"
   },
   {  
      "country":"Liechtenstein",
      "council_code":"osce",
      "allot":"0",
      "id":"383"
   },
   {  
      "country":"Lithuania",
      "council_code":"osce",
      "allot":"1",
      "id":"384"
   },
   {  
      "country":"Luxembourg",
      "council_code":"osce",
      "allot":"1",
      "id":"385"
   },
   {  
      "country":"Malta",
      "council_code":"osce",
      "allot":"1",
      "id":"386"
   },
   {  
      "country":"Moldova",
      "council_code":"osce",
      "allot":"1",
      "id":"387"
   },
   {  
      "country":"Monaco",
      "council_code":"osce",
      "allot":"1",
      "id":"388"
   },
   {  
      "country":"Mongolia",
      "council_code":"osce",
      "allot":"1",
      "id":"389"
   },
   {  
      "country":"Montenegro",
      "council_code":"osce",
      "allot":"0",
      "id":"390"
   },
   {  
      "country":"Morocco",
      "council_code":"osce",
      "allot":"1",
      "id":"391"
   },
   {  
      "country":"Netherlands",
      "council_code":"osce",
      "allot":"1",
      "id":"392"
   },
   {  
      "country":"Norway",
      "council_code":"osce",
      "allot":"1",
      "id":"393"
   },
   {  
      "country":"Poland",
      "council_code":"osce",
      "allot":"1",
      "id":"394"
   },
   {  
      "country":"Portugal",
      "council_code":"osce",
      "allot":"1",
      "id":"395"
   },
   {  
      "country":"Romania",
      "council_code":"osce",
      "allot":"1",
      "id":"396"
   },
   {  
      "country":"Russian Federation",
      "council_code":"osce",
      "allot":"1",
      "id":"397"
   },
   {  
      "country":"San Marino",
      "council_code":"osce",
      "allot":"1",
      "id":"398"
   },
   {  
      "country":"Serbia",
      "council_code":"osce",
      "allot":"0",
      "id":"399"
   },
   {  
      "country":"Slovakia",
      "council_code":"osce",
      "allot":"1",
      "id":"400"
   },
   {  
      "country":"Slovenia",
      "council_code":"osce",
      "allot":"0",
      "id":"401"
   },
   {  
      "country":"South Korea",
      "council_code":"osce",
      "allot":"1",
      "id":"402"
   },
   {  
      "country":"Spain",
      "council_code":"osce",
      "allot":"1",
      "id":"403"
   },
   {  
      "country":"Sweden",
      "council_code":"osce",
      "allot":"1",
      "id":"404"
   },
   {  
      "country":"Switzerland",
      "council_code":"osce",
      "allot":"1",
      "id":"405"
   },
   {  
      "country":"Tajikistan",
      "council_code":"osce",
      "allot":"0",
      "id":"406"
   },
   {  
      "country":"Thailand",
      "council_code":"osce",
      "allot":"1",
      "id":"407"
   },
   {  
      "country":"the former Yugoslav Republic of Macedonia",
      "council_code":"osce",
      "allot":"1",
      "id":"408"
   },
   {  
      "country":"Tunisia",
      "council_code":"osce",
      "allot":"1",
      "id":"409"
   },
   {  
      "country":"Turkey",
      "council_code":"osce",
      "allot":"1",
      "id":"410"
   },
   {  
      "country":"Turkmenistan",
      "council_code":"osce",
      "allot":"0",
      "id":"411"
   },
   {  
      "country":"Ukraine",
      "council_code":"osce",
      "allot":"1",
      "id":"412"
   },
   {  
      "country":"United Kingdom",
      "council_code":"osce",
      "allot":"1",
      "id":"413"
   },
   {  
      "country":"United States",
      "council_code":"osce",
      "allot":"1",
      "id":"414"
   },
   {  
      "country":"Uzbekistan",
      "council_code":"osce",
      "allot":"0",
      "id":"415"
   },
   {
      "country":"chair",
      "council_code":"tll",
      "allot":"1",
      "id":"chair23"
   },
   {
      "country":"vice_chair",
      "council_code":"tll",
      "allot":"1",
      "id":"vice_chair53"
   },
   {
      "country":"director",
      "council_code":"tll",
      "allot":"1",
      "id":"director83"
   },
   {  
      "country":" George Sabra",
      "council_code":"tll",
      "allot":"0",
      "id":"416"
   },
   {  
      "country":"Admiral Dennis B. Blair",
      "council_code":"tll",
      "allot":"1",
      "id":"417"
   },
   {  
      "country":"Admiral Giampaolo Di Paola",
      "council_code":"tll",
      "allot":"1",
      "id":"418"
   },
   {  
      "country":"Amartya Sen",
      "council_code":"tll",
      "allot":"1",
      "id":"419"
   },
   {  
      "country":"Angela Merkel",
      "council_code":"tll",
      "allot":"1",
      "id":"420"
   },
   {  
      "country":"Benjamin Netanyahu",
      "council_code":"tll",
      "allot":"0",
      "id":"421"
   },
   {  
      "country":"Christine Lagarde",
      "council_code":"tll",
      "allot":"1",
      "id":"422"
   },
   {  
      "country":"Count Herman Van Rompuy",
      "council_code":"tll",
      "allot":"0",
      "id":"423"
   },
   {  
      "country":"David Rockefeller",
      "council_code":"tll",
      "allot":"1",
      "id":"424"
   },
   {  
      "country":"E. Gerald Corrigan",
      "council_code":"tll",
      "allot":"1",
      "id":"425"
   },
   {  
      "country":"Elon Musk",
      "council_code":"tll",
      "allot":"1",
      "id":"426"
   },
   {  
      "country":"Eric Schmidt",
      "council_code":"tll",
      "allot":"1",
      "id":"427"
   },
   {  
      "country":"Francois Hollende",
      "council_code":"tll",
      "allot":"1",
      "id":"428"
   },
   {  
      "country":"George W Bush",
      "council_code":"tll",
      "allot":"1",
      "id":"429"
   },
   {  
      "country":"Haider Al Abadi",
      "council_code":"tll",
      "allot":"0",
      "id":"430"
   },
   {  
      "country":"Henry A. Kissinger",
      "council_code":"tll",
      "allot":"1",
      "id":"431"
   },
   {  
      "country":"Hong Seok-Hyun",
      "council_code":"tll",
      "allot":"1",
      "id":"432"
   },
   {  
      "country":"Hwang Kyo-ahn",
      "council_code":"tll",
      "allot":"0",
      "id":"433"
   },
   {  
      "country":"James Mattis",
      "council_code":"tll",
      "allot":"1",
      "id":"434"
   },
   {  
      "country":"Jean-Claude Trichet",
      "council_code":"tll",
      "allot":"1",
      "id":"435"
   },
   {
      "country":"OC",
      "council_code":"tll",
      "allot":"1",
      "id":"mofo"
   },
   {  
      "country":"Jean-Louis Bourlanges",
      "council_code":"tll",
      "allot":"0",
      "id":"436"
   },
   {  
      "country":"Jean-Louis Bruguiegravere",
      "council_code":"tll",
      "allot":"0",
      "id":"437"
   },
   {  
      "country":"Jerzy Kozminski",
      "council_code":"tll",
      "allot":"0",
      "id":"438"
   },
   {  
      "country":"John J. Hamre",
      "council_code":"tll",
      "allot":"1",
      "id":"439"
   },
   {  
      "country":"Joseph S. Nye, Jr.",
      "council_code":"tll",
      "allot":"1",
      "id":"440"
   },
   {  
      "country":"Juumlrgen Fitschen",
      "council_code":"tll",
      "allot":"0",
      "id":"441"
   },
   {  
      "country":"Justin Trudeau",
      "council_code":"tll",
      "allot":"1",
      "id":"442"
   },
   {  
      "country":"Li Zhaoxing",
      "council_code":"tll",
      "allot":"0",
      "id":"443"
   },
   {  
      "country":"Lori Esposito Murray",
      "council_code":"tll",
      "allot":"1",
      "id":"444"
   },
   {  
      "country":"Lu Shumin",
      "council_code":"tll",
      "allot":"1",
      "id":"445"
   },
   {  
      "country":"Madeleine K. Albright",
      "council_code":"tll",
      "allot":"1",
      "id":"446"
   },
   {  
      "country":"Manohar Parrikar",
      "council_code":"tll",
      "allot":"0",
      "id":"447"
   },
   {  
      "country":"Manuel Muntildeiz",
      "council_code":"tll",
      "allot":"0",
      "id":"448"
   },
   {  
      "country":"Meghan L. OrsquoSullivan",
      "council_code":"tll",
      "allot":"1",
      "id":"449"
   },
   {  
      "country":"Michael Schaefer",
      "council_code":"tll",
      "allot":"1",
      "id":"450"
   },
   {  
      "country":"Minoru Makihara",
      "council_code":"tll",
      "allot":"0",
      "id":"451"
   },
   {  
      "country":"N.K. Singh",
      "council_code":"tll",
      "allot":"1",
      "id":"452"
   },
   {  
      "country":"Peter Sutherland",
      "council_code":"tll",
      "allot":"1",
      "id":"453"
   },
   {  
      "country":"Raghuram Rajan",
      "council_code":"tll",
      "allot":"1",
      "id":"454"
   },
   {  
      "country":"Recep Triyip Erdogan",
      "council_code":"tll",
      "allot":"1",
      "id":"455"
   },
   {  
      "country":"Richard N. Haass",
      "council_code":"tll",
      "allot":"1",
      "id":"456"
   },
   {  
      "country":"Rouhani Hassan",
      "council_code":"tll",
      "allot":"1",
      "id":"457"
   },
   {  
      "country":"Shashi Tharoor",
      "council_code":"tll",
      "allot":"1",
      "id":"458"
   },
   {  
      "country":"Shigemitsu Sugisaki",
      "council_code":"tll",
      "allot":"0",
      "id":"459"
   },
   {  
      "country":"Shinzo Abe",
      "council_code":"tll",
      "allot":"1",
      "id":"460"
   },
   {  
      "country":"Theresa May",
      "council_code":"tll",
      "allot":"1",
      "id":"461"
   },
   {  
      "country":"Thomas R. Pickering",
      "council_code":"tll",
      "allot":"1",
      "id":"462"
   },
   {  
      "country":"Volker Perthes",
      "council_code":"tll",
      "allot":"1",
      "id":"463"
   },
   {  
      "country":"Wu Jianmin",
      "council_code":"tll",
      "allot":"0",
      "id":"464"
   },
   {  
      "country":"Yasuchika Hasegawa",
      "council_code":"tll",
      "allot":"0",
      "id":"465"
   },
   {  
      "country":"Zanny Minton Beddoes",
      "council_code":"tll",
      "allot":"1",
      "id":"466"
   },
   {  
      "country":"Vietnam",
      "council_code":"disec",
      "allot":"1",
      "id":"467"
   }
]